### ISSUE TITLE
DH parameters are not needed with TLSv1.2

### ISSUE THREAD

**Issue by ricardobranco777** [MarvAmBass/docker-nginx-registry-proxy#6]
The Go language crypto/tls package only implements TLSv1.2.  Diffie Hellman parameteres are not needed with TLSv1.2.

https://golang.org/pkg/crypto/tls/

**Comment by MarvAmBass** [comment]
yeah well, but there is the nginx infront of the registry - which means the client establishes the ssl connection with the nginx which has a internal ssl connection to the registry.

therefore I think I need to use DH, right?

**Comment by ricardobranco777** [comment]
The Docker client uses TLSv1.2 anyway.

**Comment by MarvAmBass** [comment]
well good point, but is this a bug on my side - or just unused or unnecessary junk in the config?

**Comment by ricardobranco777** [comment]
Unnecesary junk in the config ;)

**Comment by MarvAmBass** [comment]
good to here so it's no security risk - but thanks for figuring that out

-> omg I hate tls - you never stop learning something new - and every version has its own specialities to keep in mind... :smile:

**Comment by ricardobranco777** [comment]
Just to be safe, it would be nice to add "ssl_protocols TLSv1.2;" to ssl.conf.

**Comment by MarvAmBass** [comment]
good point, but I can't do that that easy. It's in the parent image which needs to support more TLS versions as it is used by different kind of applications out there

**Comment by ricardobranco777** [comment]
DH parameters are used for DHE ciphers as well, so you may ignore this whole thread.
