### ISSUE TITLE
make docker pull outside auth zone in nginx config

### ISSUE THREAD

**Issue by hacor** [MarvAmBass/docker-nginx-registry-proxy#9]
Hello,

Would it be possible to change the nginx.conf file in a way that the docker pull doesn't require authentication?

It would be interesting for me to require login for upload and  not-logged-in user capability to download the image from the registry

Best regards!

Hacor

**Comment by MarvAmBass** [comment]
the only reason for this image was to require authentication.

feel free to fork it and modify it to your needs.

sounds like you could use a nginx authentication script which checks if you need authentication or not

good luck shouldn't be that much work
